In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
smp_df = pd.read_csv("../data/smp_courses.csv")
onde_df = pd.read_csv("../data/ondemand_courses.csv")
we_df = pd.read_csv("../data/we_courses.csv")
panya_df = pd.read_csv("../data/panya_courses.csv")
physicsbp_df = pd.read_csv("../data/physicsblueprint_courses.csv")

In [13]:
df = pd.concat([smp_df, onde_df, we_df, panya_df, physicsbp_df], ignore_index=True)
df.shape

(447, 10)

In [14]:
print(df['institute_name'].value_counts(normalize=True) * 100)

institute_name
WE By The Brain      35.570470
SmartMathPro         28.859060
Panya Society        15.212528
OnDemand             10.290828
Physics Blueprint    10.067114
Name: proportion, dtype: float64

In [16]:
df.head()

,institute_name,course_name,tutor,subject,course_type,learning_format,total_hours,price,price_per_hour,url
0,SmartMathPro,PACK TPAT1 (ครบ 3 พาร์ต) + A-Level คณิต 1 (V.เ...,"พี่ปั้น SmartMathPro, อ.ขลุ่ย, พี่หนู, พี่ฟาร์...",คณิตศาสตร์,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์),661.0,23450.0,35.48,https://online.smartmathpro.com/product/c032/
1,SmartMathPro,พิชิตคณิตพื้นฐาน ม.4,พี่ปั้น SmartMathPro,คณิตศาสตร์,ติวเนื้อหา/เสริมเกรด,วิดีโอ (ออนไลน์),20.0,790.0,39.50,https://online.smartmathpro.com/product/f015/
2,SmartMathPro,พิชิตการนับและความน่าจะเป็น,พี่ปั้น SmartMathPro,อื่นๆ,ติวเนื้อหา/เสริมเกรด,วิดีโอ (ออนไลน์),24.0,1390.0,57.92,https://online.smartmathpro.com/product/f011/
3,SmartMathPro,พิชิตตรีโกณมิติ,พี่ปั้น SmartMathPro,อื่นๆ,ติวเนื้อหา/เสริมเกรด,วิดีโอ (ออนไลน์),38.0,1590.0,41.84,https://online.smartmathpro.com/product/f007/
4,SmartMathPro,พิชิต TPAT1 (พาร์ตเชื่อมโยง&เชาวน์ไทย),อ.ขลุ่ย,ความถนัด/TGAT/TPAT,ติวเนื้อหา/เสริมเกรด,วิดีโอ (ออนไลน์),22.0,1190.0,54.09,https://online.smartmathpro.com/product/c006/

In [17]:
df.isna().sum()

institute_name      0
course_name         0
tutor              68
subject             0
course_type         0
learning_format     0
total_hours         0
price               0
price_per_hour      0
url                 0
dtype: int64

In [18]:
df[df['tutor'].isna()]

,institute_name,course_name,tutor,subject,course_type,learning_format,total_hours,price,price_per_hour,url
130,OnDemand,Pack จับคู่ UpSkill 2 วิชา (เลข ฟิสิกส์),NaN,ฟิสิกส์,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์/สาขา),90.0,6900.0,76.67,https://shoponline.ondemand.in.th/20024149cv.html
158,OnDemand,Davance: คอร์ส TURBO สรุป ไทย+สังคม,NaN,อื่นๆ,ติวเนื้อหา/เสริมเกรด,วิดีโอ (ออนไลน์/สาขา),74.0,5200.0,70.27,https://shoponline.ondemand.in.th/20021803.html
163,OnDemand,Pack กลุ่มอะตอม ตารางธาตุ และพันธะเคมี,NaN,เคมี,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์/สาขา),84.5,4300.0,50.89,https://shoponline.ondemand.in.th/20014059cv.html
334,Panya Society,Pack สอบติด คอร์ส คณิตศาสตร์ A-Level + TGAT,NaN,คณิตศาสตร์,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์),265.0,5490.0,20.72,https://panyasociety.com/course/preview/133
335,Panya Society,สอวน. เคมีโอลิมปิก,NaN,เคมี,ติวเนื้อหา/เสริมเกรด,วิดีโอ (ออนไลน์),45.0,2990.0,66.44,https://panyasociety.com/course/preview/168
...,...,...,...,...,...,...,...,...,...,...
397,Panya Society,สอวน. คอมพิวเตอร์โอลิมปิก,NaN,อื่นๆ,ติวเนื้อหา/เสริมเกรด,วิดีโอ (ออนไลน์),60.0,2990.0,49.83,https://panyasociety.com/course/preview/167
398,Panya Society,TPAT3 ความถนัดด้านวิทยาศาสตร์ เทคโนโลยี และวิศ...,NaN,ความถนัด/TGAT/TPAT,ติวเนื้อหา/เสริมเกรด,วิดีโอ (ออนไลน์),34.0,2490.0,73.24,https://panyasociety.com/course/preview/124
399,Panya Society,Pack เพิ่มเกรด ม.4 - ฟิสิกส์,NaN,ฟิสิกส์,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์),92.0,3490.0,37.93,https://panyasociety.com/course/preview/169
400,Panya Society,Pack FAST เคมี + คณิตศาสตร์ A-Level,NaN,คณิตศาสตร์,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์),24.0,2990.0,124.58,https://panyasociety.com/course/preview/154
401,Panya Society,คณิตศาสตร์ TCAS ติดอาวุธลับ UpScore,NaN,คณิตศาสตร์,ติวสอบ A-Level/TCAS,วิดีโอ (ออนไลน์),53.0,2490.0,46.98,https://panyasociety.com/course/preview/111

In [22]:
df[(df['institute_name'] == 'OnDemand') & (df['tutor'].isna())]

,institute_name,course_name,tutor,subject,course_type,learning_format,total_hours,price,price_per_hour,url
130,OnDemand,Pack จับคู่ UpSkill 2 วิชา (เลข ฟิสิกส์),NaN,ฟิสิกส์,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์/สาขา),90.0,6900.0,76.67,https://shoponline.ondemand.in.th/20024149cv.html
158,OnDemand,Davance: คอร์ส TURBO สรุป ไทย+สังคม,NaN,อื่นๆ,ติวเนื้อหา/เสริมเกรด,วิดีโอ (ออนไลน์/สาขา),74.0,5200.0,70.27,https://shoponline.ondemand.in.th/20021803.html
163,OnDemand,Pack กลุ่มอะตอม ตารางธาตุ และพันธะเคมี,NaN,เคมี,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์/สาขา),84.5,4300.0,50.89,https://shoponline.ondemand.in.th/20014059cv.html

In [27]:
df[(df['tutor'].isna()) & (df['institute_name'] == 'Panya Society')]

,institute_name,course_name,tutor,subject,course_type,learning_format,total_hours,price,price_per_hour,url
334,Panya Society,Pack สอบติด คอร์ส คณิตศาสตร์ A-Level + TGAT,NaN,คณิตศาสตร์,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์),265.0,5490.0,20.72,https://panyasociety.com/course/preview/133
335,Panya Society,สอวน. เคมีโอลิมปิก,NaN,เคมี,ติวเนื้อหา/เสริมเกรด,วิดีโอ (ออนไลน์),45.0,2990.0,66.44,https://panyasociety.com/course/preview/168
336,Panya Society,สอวน. ฟิสิกส์โอลิมปิก,NaN,ฟิสิกส์,ติวเนื้อหา/เสริมเกรด,วิดีโอ (ออนไลน์),51.0,2990.0,58.63,https://panyasociety.com/course/preview/127
337,Panya Society,Pack สอบติด คอร์ส คณิตศาสตร์ 2 A-Level + TGAT,NaN,คณิตศาสตร์,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์),123.0,3990.0,32.44,https://panyasociety.com/course/preview/134
338,Panya Society,Pack FAST ฟิสิกส์ + เคมี A-Level,NaN,ฟิสิกส์,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์),21.0,2990.0,142.38,https://panyasociety.com/course/preview/153
...,...,...,...,...,...,...,...,...,...,...
397,Panya Society,สอวน. คอมพิวเตอร์โอลิมปิก,NaN,อื่นๆ,ติวเนื้อหา/เสริมเกรด,วิดีโอ (ออนไลน์),60.0,2990.0,49.83,https://panyasociety.com/course/preview/167
398,Panya Society,TPAT3 ความถนัดด้านวิทยาศาสตร์ เทคโนโลยี และวิศ...,NaN,ความถนัด/TGAT/TPAT,ติวเนื้อหา/เสริมเกรด,วิดีโอ (ออนไลน์),34.0,2490.0,73.24,https://panyasociety.com/course/preview/124
399,Panya Society,Pack เพิ่มเกรด ม.4 - ฟิสิกส์,NaN,ฟิสิกส์,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์),92.0,3490.0,37.93,https://panyasociety.com/course/preview/169
400,Panya Society,Pack FAST เคมี + คณิตศาสตร์ A-Level,NaN,คณิตศาสตร์,คอร์สแพ็กเกจ,วิดีโอ (ออนไลน์),24.0,2990.0,124.58,https://panyasociety.com/course/preview/154
401,Panya Society,คณิตศาสตร์ TCAS ติดอาวุธลับ UpScore,NaN,คณิตศาสตร์,ติวสอบ A-Level/TCAS,วิดีโอ (ออนไลน์),53.0,2490.0,46.98,https://panyasociety.com/course/preview/111